### PR TITLE
Require Python 3.7+, fix test failures, test against Py 3.10 and 3.11, README/RELEASE update

### LINKED ISSUE #12: Fix CI test failures
When switching to GitHub actions from TravisCI I successfully broke the test suite without understanding why, see #10.

Any ideas on what went wrong? [Here is a failing test run](https://github.com/yuvipanda/simpervisor/runs/1648380198?check_suite_focus=true).

### LINKED ISSUE #15: Provide a non-technical introduction paragraph in the readme
The README of this project needs some love. I'm especially looking for an introduction to what this is for anyone in the jupyterhub org looking to help out with maintenance and for users to help understand if this is relevant to them etc.

> - [ ] Provide a non-technical introduction paragraph helping anyone understand its role in the JupyterHub ecosystem and purpose without themselves needing to understand much technical details.

I extracted that suggested action point from #13 that I closed

### PR DESCRIPTION
**Pull request by consideRatio**
Based on #18 to avoid merge conflicts. Excluding that #18, this PR involves a flurry of minor fixes.

- ci: fix failure to test old python versions
- Transition to hatchling/pyproject.toml from setuptools/setup.py 
- Let module include `__version__`
- Fix typo in comment
- Add a basic description to the README
  Closes #15
- Use relative module imports within the module
  Closes #12
- ci: reduce verbosity of pytest
- Update RELEASE.md and rely on tbump
- Drop support for Python 3.6
- Adopt python 3.7 text=True for subprocess.Popen
- docs: increase development status beyond beta
- ci: resolve intermittent test failures by sleeping longer
  Properly closes #12

## DRAFT

Currently working to fix test failing intermittently

### CODE REVIEW

**Comment by yuvipanda** [comment]
@consideRatio do we use hatchling in other Jupyter projects already?  Also I merged #18, but github doesn't seem to acknowledge that here in showiong me diffs :(

**Comment by consideRatio** [comment]
Thanks @yuvipanda!!!

I saw @minrk start to use it in https://github.com/minrk/jupyter-keepalive/blob/main/pyproject.toml so that is my inspiration towards this.

**Comment by consideRatio** [comment]
I'm not sure, do you need that defined at all? Would it work to remove it entirely and have a pyproject.toml without hatchling defined as a build system?

**Review by yuvipanda — APPROVED** [review]
@consideRatio so I'm totally lost on pyproject.toml in general, and haven't been keeping up :) My only requirement is that 'editable installs' (`pip install -e .`) work. If it does for hatchling, happy to give it a shot here :) Do you know if it does? I can't seem to find info...

**Comment by consideRatio** [comment]
image

I'm quite lost as well, but I think this is fine! I'm happy to avoid having setup.py, setup.cfg, pyproject.toml all side by side. If adding hatchling to pyproject.toml makes us able to remove the setup.py thats nice.

I think can't use Python 3.5 and remove setup.py going for only pyproject.toml + a declared build-system, but you can if you have python 3.6+! So, this pattern is something we can adopt wider as well I think.

**Comment by yuvipanda** [comment]
Thanks, @consideRatio! If `pip install -e .` works I'm happy to try :)

**Comment by consideRatio** [comment]
Wiee thanks for your quick review of this @yuvipanda, greatly appreciated!!! :heart: :tada:

**Comment by minrk** [comment]
I've been exploring hatchling, which is kinda the PyPA successor to flit, but with hooks for optional build steps. It's being adopted in the JupyterLab/jupyter-releaser projects, so there's a plugin to build jupyterlab extensions, so we don't have to cargo-cult our npm build steps around everywhere in setup.py. That's why I picked it for jupyter-keepalive. I probably would have stuck with setuptools in keepalive were it not for the lab extension.

If you have a simple Python-only package like this one, there isn't really a difference between using setuptools and hatchling with pyproject.toml. You don't need setup.py with either one, but if you have setup.py with setuptools, it's the two-line `from setup.py import setup; setup()` since you can put all your metadata in pyproject.toml's `[project]` section instead of args to setup.

`pip install -e` does work for pyproject.toml installs, thanks to [pep 660](https://peps.python.org/pep-0660/).

As I understand hatchling more, I think we can make the jupyterhub build/install much _simpler_ than the complicated steps we have now.

**Pull request merged**
